### PR TITLE
builder-module: run autotools tests in parallel

### PR DESCRIPTION
**Pull request by lw64**

### CODE REVIEW

**Comment by lw64** [comment]
I am not sure if parallel tests should be also enabled for other build systems.

**Comment by TingPing** [comment]
The same `-j` arguments apply to both cmake and meson.

**Comment by lw64** [comment]
I think Meson is doing it by default though. Should it still be given there too?

**Comment by TingPing** [comment]
Yes, `ninja` defaults to number of threads + 2 or similar.

However I think this is a bugfix, because now it will respect limits you give `flatpak-builder`.

**Comment by lw64** [comment]
Thanks! Is there going to be a release with this fix soon?

**Pull request merged**
