### PR TITLE
source-git: Add option to disable submodules

### PR DESCRIPTION
**Pull request by lnjX**

### CODE REVIEW

**Comment by JBBgameich** [comment]
This is useful to prevent unnecessary issues introduced by trying to check out submodules even if they are not needed. Example: https://binary-factory.kde.org/job/Kaidan_flatpak/77/console

**Comment by mwleeds** [comment]
Looks like this needs to be documented in `doc/flatpak-manifest.xml`

**Comment by lnjX** [comment]
@mwleeds Done :)

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
