### PR TITLE
Add SVN source type

### PR DESCRIPTION
**Pull request by alexlarsson**
This adds support for SVN sources, fixing https://github.com/flatpak/flatpak-builder/issues/133

@magicmyth does this look ok to you?

### CODE REVIEW

**Comment by alexlarsson** [comment]
bot, retest this please

**Comment by alexlarsson** [comment]
I actually want to make a flatpak for flatpak-builder, but that won't have the patch anyway. However, you don't need to rebuild flatpak, only flatpak-builder.

**Comment by alexlarsson** [comment]
Oh, and yeah, that is right, but you have to add a url too, and "revision" is optional (defaults to latest).

**Comment by magicmyth** [comment]
Thanks for getting back quick. I totally would have built flatpak instead of flatpak builder and been scratching my head.

I've just done a quick test with the following manifest:
```
{
  "app-id": "lets.test.svn",
  "runtime": "org.freedesktop.Platform",
  "runtime-version": "1.6",
  "sdk": "org.freedesktop.Sdk",
  "command": "not-real",
  "finish-args": [
     "--filesystem=home"
  ],
  "modules": [
    {
      "name": "radiant-paks",
      "buildsystem": "simple",
      "sources": [
        {
          "type": "svn",
          "url": "svn://svn.icculus.org/gtkradiant-gamepacks/Q1Pack/trunk",
          "revision": "16",
          "dest": "gamepacks/Q1Pack"
        },
        {
          "type": "svn",
          "url": "svn://svn.icculus.org/gtkradiant-gamepacks/Q2Pack/branches/1.4",
          "dest": "gamepacks/Q2Pack"
        },
        {
          "type": "svn",
          "url": "svn://svn.icculus.org/gtkradiant-gamepacks/Q3Pack/trunk",
          "dest": "gamepacks/Q3Pack"
        },
        {
          "type": "archive",
          "url": "https://downloads.sourceforge.net/project/liboauth/liboauth-1.0.3.tar.gz",
          "sha256": "0df60157b052f0e774ade8a8bac59d6e8d4b464058cc55f9208d72e41156811f"
        }
      ],
      "build-commands": [
        "pwd",
        "ls",
        "echo 'Check if the packs are there'",
        "ls gamepacks",
        "exit 1"
      ]
    }
  ]
}
```

and it worked perfectly! The liboauth source is just so I could test mixing the sources in the way I intend to with GtkRadiant. I can confirm the checkout caches are working and as you can see I tested with a revision, branch and trunk checkouts. All worked as expected.

No idea how you made that work so darn quick but thanks!

**Comment by magicmyth** [comment]
I meant to say that when trying to build flatpak-builder there was no `configure` script. Running `./autogen.sh` fixed that but its not mentioned on the README.md so maybe its worth adding that tid bit?

**Comment by alexlarsson** [comment]
The configure script is only in the release tarball, if you're building from git you have to use autogen.sh. This is pretty standard, but maybe the readme should mention it.

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
