### PR TITLE
[RFC] Add support for FTP sources using libcurl

### PR DESCRIPTION
**Pull request by larchunix**
Here is a possible implementation for downloading FTP sources using `libcurl` (MIT licensed).

@alexlarsson: Could you give me some feedback ? I would like to know if you think it is upstreamable before spending more time on it.

### CODE REVIEW

**Comment by TingPing** [comment]
Couldn't it just be a runtime dep using the `curl` tool similar to the other source types?

**Comment by alexlarsson** [comment]
Looks good to me. Although i wonder if we should just drop libsoup support altogether instead? Then we get things like HTTP2 support

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Comment by alexlarsson** [comment]
Oh, you need to add `libcurl-devel` to `ci/build.sh`.

**Comment by alexlarsson** [comment]
bot, add author to whitelist

**Comment by larchunix** [comment]
bot, retest this please

**Comment by TingPing** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
